name: qa

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:


jobs:
  go-lint:
    runs-on: ubuntu-latest
    name: Go linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
  go-vuln:
    runs-on: ubuntu-latest
    name: Go vulnerability check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - id: govulncheck
        uses: golang/govulncheck-action@v1
  go-test:
    runs-on: ubuntu-latest
    name: Go testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test ./...
